language: python

deploy:
  provider: pypi
  user: __token__
  password:
    secure: vOOVU7kfCgWw+9la6HcccHwujlv/3Qs5sWAj306TOnvW6erTP/OBlCcNm0WDrlPZJKPciH/9wZJcXCVRViM9R+CDF8HvHAyP1Uha6+bQQM3IDHw4GtpI1yHC7T7WkGWatqzRfBAPUq4aDifo/zWIdufTWwYXmBmJbCbZrCsfd+nerL+PCbgNBkORHOsEbatCqmxYXx+bwW/dCkOGERwfK5HymHUngPdlWgaUrmI3uCW2ydblGnlRIlFtcoLpp13KUmH0fwobJrJKUOLpHK3OsC9dZvYO9mwMEwpiZTkVZXqW6y47PmtE48j51a91F+1vkDVV/xw0muYdg7vht5Os0VNcOSwruYG2T+34V9iy/XAMizJk6EiOuo3cYwxJRnyUkS5lJEQzIVen2RB5B+4Q26ukd6bm+Go47KnzadIefg4eJFqqMghx6EhM/dXG3eouKNwp5N/XJ3iWhjJRrtPD4y/XsCGBr/SBjiUGonHW+8IVDnPPicB2SMl4BxcDoSsVw0quHvz9mB6x9sZRkuKTLr5B9yz10xbIZM9NmCwdLUegK8xX9D1gr/bcwYpDWb1vM3ocDGGY+QEs91GffAGKrkT3PKTqA8yTJrKDxaVczPLy88ohS5XFHPqcDjqwx614JWAAQSUUTHKCCR0gZ6SQaW093DySeco15sj7cGlW8aA=
  on:
    branch: production
