language: python

python:
  - '3.6'

install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=. python  -m unittest discover tests
  - python setup.py install
deploy:
  provider: pypi
  user: __token__
  password:
    secure: eIvPZVj9COUX0aeLy+eQH7cjBZ0m8JUw/qKBkUkQFZ6NiggmIPpiOGyypuxorczUUSfBsiU1emDies5eE+Nza8NRFM2OfvTbKszyIEFnan4E7WLhsS4EZvNhdAuzWubMJ1Bm24LyhrfcG8kB9UQ4qpCEuSRKKWq0crgcJDGlcI8eRsDZxt/JczK/MVdcDu/bVReAnsSQxuFcKwe14/Q8NF+TuA4FHot21qPAZFTlJo7X45WV7NHNl7XGo0ddSlRew63bJWB0HUwiVylB/MHcb3zY1K9EFRgPLVZ6tSfAcR7suSsHol5aiiit/tTzqhcjnFkUEZtw1pNWSMbnJgB1Oao0IK7ZBbgerznc0T0zu2gyrG8F7ZEP8/EMCHAxpyJesNDHjlnYN7hTxD4f8ehmkbZtixgEYjVOZCPXG+9pISkypc7Lqudm2kep3sbGEBqkrrj89hw5V2xZH3cg3K2bNBh+EhUNXGn/rxcC/zEHQCyI7TcF78A/ivvBC4kemr0CRRf15KkDn5fYji42l1AVOEBnyd8BZwhIgL4MDW9vX+UQSr2u5i12aq50+jM1TGdgxKKHQMtUJ5WvtBWCbE/ZjxWRDyvjxuxtDGjYAoLsqviPGlFgSa1+asJcnex80jzGHU5FVpXe52N+2uFtGnzW+pHaHaz2cQbkZfMr1sWCIg8=
  on:
    branch: production
